name: biotec-fisica
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandoc
  - nodejs>=20
  - git
  - jupyterlab
  # - quarto
  - pip
  - pyyaml
  - pre-commit
  - pip:
      - mystmd
      # - jupyter-book
